export default [
    'anxiety',
    'bpm',
    'calories',
    'coffee',
    'distance',
    'exercise',
    'finances',
    'gas',
    'knee push ups',
    'mental energy',
    'milage',
    'mood',
    'pace',
    'physical energy',
    'pull ups',
    'push ups',
    'sleep',
    'todo',
    'water',
    'weight',
    'wide arm push ups',
]
